<?php $_cartQty = $this->getSummaryCount() ?>
<div id ="mini_cart_block">
    <div class="block-cart mini_cart_ajax">
            <div class="block-cart">
                <?php $_cartQty = $this->getSummaryCount() ?>
                <div class="cart-mini-title">
                    <a class="shopping-cart hidden-xs" href="<?php echo Mage::helper('checkout/cart')->getCartUrl(); ?>">
                    <span class="cart-count"><?php if($_cartQty<1) { echo $this->__('0'); } else { echo $_cartQty; } ?></span>
						<span class="cartText hidden-xs">Cart</span>
					</a>
					<a class="shopping-cart visible-xs hidden-sm" href="<?php echo "javascript:void(0)" ?>">
                    <span class="cart-count"><?php if($_cartQty<1) { echo $this->__('0'); } else { echo $_cartQty; } ?></span>
						<span class="cartText hidden-xs">Cart</span>
					</a>
                </div>
				<div class="top-line"></div>
                <div class="top-cart-content">
                    <?php $_items = $this->getRecentItems() ?>
                    <?php if (count($_items)): ?>
                        <ol id="cart-sidebar" class="mini-products-list">
                            <?php foreach ($_items as $_item): ?>
                                <?php echo $this->getItemHtml($_item) ?>
                            <?php endforeach; ?>
                        </ol>
                        <script type="text/javascript">decorateList('cart-sidebar', 'none-recursive')</script>
                        <script type="text/javascript">
                            jQuery(document).ready(function ($j) {
                                $j("#cart-sidebar .item").each(function(){
                                    var $itemBox = $j(this).children(".product-details");
                                    var $qtyBox = $j(this).find(".product-qty");
                                    var qty;
                                    $itemBox.find(".qtyBtn").click(function(){
                                        if($j(this).hasClass("qtyAdd")){
                                            qty = parseInt($qtyBox.text())+1;
                                            $qtyBox.text(qty);
                                        }else if($j(this).hasClass("qtyReduce")){
                                            qty = parseInt($qtyBox.text());
                                            if(qty <= 1){
                                                $itemBox.find(".btn-remove").click();
                                            }else if(qty>1){
                                                qty -=1;
                                                $qtyBox.text(qty);
                                            }
                                        }
                                    });
                                });
                            });
                        </script>
                    <?php else: ?>
                        <p class="empty"><?php echo $this->__('You have no items in your shopping cart.') ?></p>
                    <?php endif ?>
                    <div class="top-subtotal"><?php echo $this->__('Subtotal') ?>: <?php echo Mage::helper('checkout')->formatPrice($this->getSubtotal()) ?></div>
                    <?php if ($_cartQty && $this->isPossibleOnepageCheckout()): ?>
                        <div class="actions clearfix">
                            <?php echo $this->getChildHtml('extra_actions') ?>
                            <a href="<?php echo Mage::helper('checkout/cart')->getCartUrl(); ?>" class="left action_cart">UPDATE</a>
                            <button type="button" title="<?php echo $this->__('Checkout') ?>" class="button right" onclick="setLocation('<?php echo $this->getCheckoutUrl() ?>')"><span><span><?php echo $this->__('Checkout') ?></span></span></button>
                        </div>
                    <?php endif ?>
                </div>
            </div>
    </div>
</div>
<script type="text/javascript">
    var ajaxCartCfg = {
        'removeConfirm' : '<?php echo $this-> __('Are you sure you would like to remove this item ?') ?>',
    };
</script>