<?php
/*
if(!$this->getConfig('enabled')) return;

$_productCollection=$this->getProductCollection();
$_helper = $this->helper('catalog/output');
$helpLabels = $this->helper('themevast/labels');
?>

<div class="newproductslider">
	<?php echo $this->getConfig('title') ? '<div class="bx-title newproduct-title"><h2>' .$this->getConfig('title'). '</h2></div>' : '';
	if(!$_productCollection->count()): ?> 
		<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
	<?php else: ?>
	<?php
		// getConfig
		$widthImage  	= $this->getConfig('widthImage') ? $this->getConfig('widthImage') : 135;
		$heightImage 	= $this->getConfig('heightImage') ? $this->getConfig('heightImage') : 135;
		$price   		= $this->getConfig('price');
		$cart    		= $this->getConfig('cart');
		$compare  		= $this->getConfig('compare');
		$wishlist  		= $this->getConfig('wishlist');
		$review  		= $this->getConfig('review');
		$rows 			= $this->getConfig('rows');
		$class 			= ($rows > 1) ? '.slide-multirows' : '.products-grid';
	?>
	<?php if ($rows > 1): ?>
		<div class="slide-multirows">
	<?php endif ?>
    <?php $_collectionSize = $_productCollection->count() ?>
    <?php $_columnCount = 2 ?>
    <?php $j=0; $time = $this->getConfig('playDelay') ? $this->getConfig('playDelay') : 0; ?>
    <?php $i=0; foreach ($_productCollection as $_product): ?>
        <?php $t = $j*$time; $t .='ms'; $j++; ?>
        <?php if ($i++%$_columnCount==0): ?>
        <ul class="products-grid">
        <?php endif ?>
            <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?> item-animate">
		<div class="item-inner">
				<?php // Product Image ?>
				<div class="box-images">
				<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
				<?php $imagehv = $_product->load('media_gallery')->getMediaGalleryImages()->getItemByColumnValue('position','2');
					if($imagehv) : 
					$imagehv = $imagehv->getFile();
					?>
				<img class="img-face-back" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image', $imagehv)->resize($widthImage, $heightImage); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
				<?php endif ?>
				<img class="img-face" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($widthImage, $heightImage); ?>" width="<?php echo $widthImage ?>" height="<?php echo $heightImage ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
				<a class="view-detail" <?php if(Mage::getStoreConfig('quickview/general/enabled')):?> id='fancybox<?php echo $_product->getId()?>'  href="<?php echo $this->getUrl('quickview/index/ajax',array('product_id'=>$_product->getId())); ?>"<?php else: ?> href="<?php echo $_product->getProductUrl() ?>" href="<?php echo $_product->getProductUrl() ?>" <?php endif ?> title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><i class="fa fa-search"></i></a>
				</div>
				<?php // Product description ?>
				<div class="product-shop">
					<?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
					<h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></h2>
					<?php if($review): ?>
						<?php echo $this->getReviewsSummaryHtml($_product) ?>
					<?php endif; ?>
					<?php if($price): ?>
							<?php echo $this->getPriceHtml($_product, true) ?>
						<?php endif; ?>
					<div class="actions">
						<?php if($cart): ?>
							<?php if($_product->isSaleable()): ?>
								<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><i class="fa fa-shopping-cart"></i><?php echo $this->__('Add to Cart') ?></span></span></button>
							<?php else: ?>
								<p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
							<?php endif; ?>
						<?php endif; ?>
						<?php if($compare || $wishlist): ?>
						<ul class="add-to-links">
							<?php if($compare): ?>
								<?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
									<li><a href="<?php echo $_compareUrl ?>" class="link-compare"><i class="fa fa-exchange"></i><?php //echo $this->__('Add to Compare') ?></a></li>
								<?php endif; ?>
							<?php endif; ?>
							<?php if($wishlist): ?>
								<?php if ($this->helper('wishlist')->isAllow()) : ?>
									<li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><i class="fa fa-heart"></i><?php //echo $this->__('Add to Wishlist') ?></a></li>
								<?php endif; ?>
							<?php endif; ?>	
						</ul>
					<?php endif; ?>
					</div>
				</div>
			<?php echo $helpLabels->getLabels($_product); //Product labels ?>
		</div>
            </li>
        <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
        </ul>
        <?php endif ?>
        <?php endforeach ?>
		<?php if ($rows > 1): ?>
		</div>
		<?php endif ?>
	<?php endif ?>
</div> 

<script type="text/javascript">
	jQuery(document).ready(function($){
		(function(selector){
			var $content = $(selector);
			var $slider  = $('<?php echo $class ?>', $content);
			var slider 	 = $slider.bxSlider({
				<?php echo $this->setBxslider() ?>
				moveSlides:1,
				slideMargin: 10,
				autoHover: true,
			})

		})(".newproductslider");
	});
</script>
<?php */?>
<?php
$webUrl = Mage::getBaseUrl();
$skinUrl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);
?>

<!--img src="<?php //echo $this->getSkinUrl('images/home/bestseller.jpg');?>" />-->
<!--best sellers begin-->
<div class="seller-Box clearfix">
	<div class="seller-Head">
		<h3>Best Sellers</h3>
	</div>
	<div class="seller-Main row clearfix">
		<div class="col-xs-12 col-lg-7 col-md-7 hidden-xs">
			<div class="seller-L1 left">
			<a href="<?php echo $webUrl."one-plus-x-lcd-white.html"?>">
				<img src="<?php echo $skinUrl?>/frontend/tv_bigboom_package/tv_bigboom1/images/new_add/seller/seller-L1.jpg" alt="">
				<i class="imgText">LCD</i>
			</a>
			</div>
			<div class="seller-L2 left">
				<a href="<?php echo $webUrl."g-sp-samsung-s8-plus-super-glass-gold.html"?>">
					<img src="<?php echo $skinUrl?>/frontend/tv_bigboom_package/tv_bigboom1/images/new_add/seller/seller-L2.jpg" alt="">
					<i class="imgText">Glass</i>
				</a>
			</div>
		</div>
		<div class="col-xs-12 col-lg-5 col-md-5">
			<div class="seller-L3">
				<a href="<?php echo $webUrl."iphone-6-wifi-ic.html"?>">
					<img src="<?php echo $skinUrl?>/frontend/tv_bigboom_package/tv_bigboom1/images/new_add/seller/seller-L31.jpg" alt="">
					<i class="imgText it1">IC</i>
				</a>
				<a href="<?php echo $webUrl."g-sp-leather-case-with-wallet-for-iphone-7.html"?>">
					<img src="<?php echo $skinUrl?>/frontend/tv_bigboom_package/tv_bigboom1/images/new_add/seller/seller-L32.jpg" alt="">
					<i class="imgText it2">Case</i>
				</a>
				<a href="<?php echo $webUrl."iphone-6-original-battery.html"?>">
					<img src="<?php echo $skinUrl?>/frontend/tv_bigboom_package/tv_bigboom1/images/new_add/seller/seller-L33.jpg" alt="">
					<i class="imgText it3">Battery</i>
				</a>
				<a href="<?php echo $webUrl."samsung-sm-g930f-s7-charge-flex.html"?>">
					<img src="<?php echo $skinUrl?>/frontend/tv_bigboom_package/tv_bigboom1/images/new_add/seller/seller-L34.jpg" alt="">
					<i class="imgText it4">Flex</i>
				</a>
			</div>
		</div>
	</div>
</div>
